#ifndef EMBEDDED_GENSET_CONTROLLER_WEB_FILE_SERVER_H
#define EMBEDDED_GENSET_CONTROLLER_WEB_FILE_SERVER_H
bool setupFilemanager(void);

#include "main.h"
#endif //EMBEDDED_GENSET_CONTROLLER_WEB_FILE_SERVER_H