; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = 16MB_12MB_FFAT_NO_OTA.csv

lib_deps = 
	holgerlembke/ESP32 File Manager for Generation Klick ESPFMfGK@^2.0.17
	bblanchon/ArduinoJson@^7.2.2
	xreef/EMailSender@^4.1.3

monitor_speed = 115200

;monitor_filters = esp32_exception_decoder
monitor_filters = direct